site_name: MiniCRM API Dokumentáció
site_url: https://baertsy.github.io/apidocstest/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Váltás sötét módra
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Váltás világos módra
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - i18n:
      languages:
        - code: hu
          name: Magyar
          build: true
          default: true
          locale: hu
        - code: en
          name: English
          build: true
          default: false
          locale: en
      nav_translations:
        en:
          Alapok: Basics
          Végpontok: Endpoints
          Cégek és Kapcsolatok: Company and Contacts
          Rendelések: Orders

nav:
  - Alapok: index.md
  - Integrációs lehetőségek : integration_options.md
  - Végpontok:
    - Cégek és Kapcsolatok: company.md
    - Rendelések: orders.md
