name: Deploy MkDocs Material

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python környezet beállítása
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: MkDocs Material és i18n modul telepítése
        run: |
          pip install mkdocs-material
          pip install mkdocs-static-i18n
      - name: Dokumentáció publikálása (gh-pages ágra)
        run: mkdocs gh-deploy --force
